#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

// Run the Artisan application...
$status = $app->handleCommand(new Symfony\Component\Console\Input\ArgvInput);

// Terminate the application and send the exit code to the shell...
$app->terminate();

exit($status);
